name: MCMultiHardcore
version: '1.0-SNAPSHOT'
main: org.PrinzAutistimus.mCMultiHardcore.MCMultiHardcore
api-version: '1.21'
dependencies:
  server:
    Multiverse-Core:
      load: BEFORE
      required: true